language: zh-TW
root: /zh-TW/
source_dir: source-i18n/zh-TW
public_dir: public/zh-TW

description: 分享 Cloudflare、AI、Python、Linux 與建站經驗

theme_config:
  menu:
    首頁: / || fas fa-home
    歸檔: /archives/ || fas fa-archive
    分類: /categories/ || fas fa-folder-open
    標籤: /tags/ || fas fa-tags
    關於我: /about/ || fas fa-user
    韌體定製: https://www.weigshare.com/wrt/ || fas fa-wifi
  subtitle:
    sub:
      - 分享 Cloudflare
      - 分享 AI 工具
      - 分享 Python
  search:
    placeholder: 搜尋文章
  aside:
    card_author:
      button:
        text: 關於我
        link: /zh-TW/about/
    card_announcement:
      content: 歡迎來到 Wei.G Share Blog 🚀
  giscus:
    option:
      data-lang: zh-TW
